In [ ]:
# https://docs.google.com/spreadsheets/d/1_TvmhWARRdmduz08ryj8G5VSFG4SJB0gReqilKEQYHE/edit?usp=sharing

In [2]:
import pandas as pd;

In [ ]:
# Installing the gspread library for connection with google sheets

In [3]:
pip install gspread;

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gspread in c:\users\dell\appdata\roaming\python\python313\site-packages (6.2.1)
Requirement already satisfied: google-auth>=1.12.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from gspread) (2.48.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in c:\users\dell\appdata\roaming\python\python313\site-packages (from gspread) (1.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\programdata\anaconda3\lib\site-packages (from google-auth>=1.12.0->gspread) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\programdata\anaconda3\lib\site-packages (from google-auth>=1.12.0->gspread) (44.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\dell\appdata\roaming\python\python313\site-packages (from google-auth>=1.12.0->gspread) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\programdata\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth>=1.12.0->gspread) (0.4.8)
Requirement already satisfied: cffi>=1.12 in c:\programdata\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth>=1.12.0->gspread) (1.17.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=1.12.0->gspread) (2.21)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\dell\appdata\roaming\python\python313\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [2]:
import gspread
print(gspread.__file__)

C:\Users\Dell\AppData\Roaming\Python\Python313\site-packages\gspread\__init__.py

In [3]:
import gspread

In [4]:
import gspread
print("gspread working perfectly ✅")

gspread working perfectly ✅

In [ ]:
# importing the gspread library

In [5]:
import gspread;

In [ ]:
# This is a optional step because its already installed in jupyter notebook

In [6]:
pip install google-auth

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: google-auth in c:\users\dell\appdata\roaming\python\python313\site-packages (2.48.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\programdata\anaconda3\lib\site-packages (from google-auth) (0.2.8)
Requirement already satisfied: cryptography>=38.0.3 in c:\programdata\anaconda3\lib\site-packages (from google-auth) (44.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\dell\appdata\roaming\python\python313\site-packages (from google-auth) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\programdata\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth) (0.4.8)
Requirement already satisfied: cffi>=1.12 in c:\programdata\anaconda3\lib\site-packages (from cryptography>=38.0.3->google-auth) (1.17.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth) (2.21)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# this is a very important step now where we are connecting the google cloud console with the jupyter notebook

In [7]:
import gspread
from google.oauth2.service_account import Credentials

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds = Credentials.from_service_account_file("b2b-sales-488816-f00097d78156.json", scopes=scope)
client = gspread.authorize(creds)

sheet = client.open("sales_pipeline").sheet1
data = sheet.get_all_records()
print(data)

[{'opportunity_id': '1C1I7A6R', 'sales_agent': 'Moses Frase', 'product': 'GTX Plus Basic', 'account': 'Cancity', 'deal_stage': 'Won', 'engage_date': '2016-10-20', 'close_date': '2017-03-01', 'close_value': 1054}, {'opportunity_id': 'Z063OYW0', 'sales_agent': 'Darcel Schlecht', 'product': 'GTXPro', 'account': 'Isdom', 'deal_stage': 'Won', 'engage_date': '2016-10-25', 'close_date': '2017-03-11', 'close_value': 4514}, {'opportunity_id': 'EC4QE1BX', 'sales_agent': 'Darcel Schlecht', 'product': 'MG Special', 'account': 'Cancity', 'deal_stage': 'Won', 'engage_date': '2016-10-25', 'close_date': '2017-03-07', 'close_value': 50}, {'opportunity_id': 'MV1LWRNH', 'sales_agent': 'Moses Frase', 'product': 'GTX Basic', 'account': 'Codehow', 'deal_stage': 'Won', 'engage_date': '2016-10-25', 'close_date': '2017-03-09', 'close_value': 588}, {'opportunity_id': 'PE84CX4O', 'sales_agent': 'Zane Levy', 'product': 'GTX Basic', 'account': 'Hatfan', 'deal_stage': 'Won', 'engage_date': '2016-10-25', 'close_date': '2017-03-02', 'close_value': 517}, {'opportunity_id': 'ZNBS69V1', 'sales_agent': 'Anna Snelling', 'product': 'MG Special', 'account': 'Ron-tech', 'deal_stage': 'Won', 'engage_date': '2016-10-29', 'close_date': '2017-03-01', 'close_value': 49}, {'opportunity_id': '9ME3374G', 'sales_agent': 'Vicki Laflamme', 'product': 'MG Special', 'account': 'J-Texon', 'deal_stage': 'Won', 'engage_date': '2016-10-30', 'close_date': '2017-03-02', 'close_value': 57}, {'opportunity_id': '7GN8Q4LL', 'sales_agent': 'Markita Hansen', 'product': 'GTX Basic', 'account': 'Cheers', 'deal_stage': 'Won', 'engage_date': '2016-11-01', 'close_date': '2017-03-07', 'close_value': 601}, {'opportunity_id': 'OLK9LKZB', 'sales_agent': 'Niesha Huffines', 'product': 'GTX Plus Basic', 'account': 'Zumgoity', 'deal_stage': 'Won', 'engage_date': '2016-11-01', 'close_date': '2017-03-03', 'close_value': 1026}, {'opportunity_id': 'HAXMC4IX', 'sales_agent': 'James Ascencio', 'product': 'MG Advanced', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-03', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'NL3JZH1Z', 'sales_agent': 'Anna Snelling', 'product': 'MG Special', 'account': 'Bioholding', 'deal_stage': 'Won', 'engage_date': '2016-11-04', 'close_date': '2017-03-10', 'close_value': 53}, {'opportunity_id': 'KWVA7VR1', 'sales_agent': 'Gladys Colclough', 'product': 'GTXPro', 'account': 'Genco Pura Olive Oil Company', 'deal_stage': 'Lost', 'engage_date': '2016-11-04', 'close_date': '2017-03-18', 'close_value': 0}, {'opportunity_id': 'S8DX3XOU', 'sales_agent': 'James Ascencio', 'product': 'GTX Plus Pro', 'account': 'Sunnamplex', 'deal_stage': 'Won', 'engage_date': '2016-11-04', 'close_date': '2017-03-10', 'close_value': 5169}, {'opportunity_id': 'ENB2XD8G', 'sales_agent': 'Maureen Marcano', 'product': 'GTX Plus Pro', 'account': 'Sonron', 'deal_stage': 'Won', 'engage_date': '2016-11-04', 'close_date': '2017-03-06', 'close_value': 4631}, {'opportunity_id': '09YE9QOV', 'sales_agent': 'Hayden Neloms', 'product': 'MG Advanced', 'account': 'Finjob', 'deal_stage': 'Won', 'engage_date': '2016-11-05', 'close_date': '2017-03-11', 'close_value': 3393}, {'opportunity_id': '3F5MZNEH', 'sales_agent': 'Rosalina Dieter', 'product': 'MG Special', 'account': 'Sonron', 'deal_stage': 'Lost', 'engage_date': '2016-11-05', 'close_date': '2017-03-03', 'close_value': 0}, {'opportunity_id': 'M6WEJXC0', 'sales_agent': 'Rosalina Dieter', 'product': 'MG Advanced', 'account': 'Scotfind', 'deal_stage': 'Won', 'engage_date': '2016-11-05', 'close_date': '2017-03-06', 'close_value': 3284}, {'opportunity_id': '6PTR7VBR', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'Treequote', 'deal_stage': 'Won', 'engage_date': '2016-11-06', 'close_date': '2017-03-05', 'close_value': 61}, {'opportunity_id': '902REDPA', 'sales_agent': 'Daniell Hammack', 'product': 'GTXPro', 'account': 'Xx-zobam', 'deal_stage': 'Lost', 'engage_date': '2016-11-07', 'close_date': '2017-03-09', 'close_value': 0}, {'opportunity_id': '5J9CMGDV', 'sales_agent': 'Elease Gluck', 'product': 'MG Special', 'account': 'Rantouch', 'deal_stage': 'Won', 'engage_date': '2016-11-07', 'close_date': '2017-03-08', 'close_value': 46}, {'opportunity_id': 'JJXRR8R6', 'sales_agent': 'James Ascencio', 'product': 'GTX Plus Pro', 'account': 'Fasehatice', 'deal_stage': 'Lost', 'engage_date': '2016-11-07', 'close_date': '2017-03-17', 'close_value': 0}, {'opportunity_id': 'WF4HA5NW', 'sales_agent': 'Moses Frase', 'product': 'MG Special', 'account': 'Ron-tech', 'deal_stage': 'Won', 'engage_date': '2016-11-07', 'close_date': '2017-03-18', 'close_value': 50}, {'opportunity_id': 'C5K2JP1H', 'sales_agent': 'Violet Mclelland', 'product': 'GTX Plus Basic', 'account': 'Vehement Capital Partners', 'deal_stage': 'Won', 'engage_date': '2016-11-07', 'close_date': '2017-03-11', 'close_value': 1014}, {'opportunity_id': 'ADRB8OMB', 'sales_agent': 'Darcel Schlecht', 'product': 'GTX Basic', 'account': 'Warephase', 'deal_stage': 'Won', 'engage_date': '2016-11-08', 'close_date': '2017-03-26', 'close_value': 561}, {'opportunity_id': 'SBCR987L', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Basic', 'account': 'Zoomit', 'deal_stage': 'Won', 'engage_date': '2016-11-10', 'close_date': '2017-03-23', 'close_value': 590}, {'opportunity_id': 'UP409DSB', 'sales_agent': 'Maureen Marcano', 'product': 'MG Advanced', 'account': 'Ganjaflex', 'deal_stage': 'Engaging', 'engage_date': '2016-11-10', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'JSD4APT2', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'Bioholding', 'deal_stage': 'Won', 'engage_date': '2016-11-10', 'close_date': '2017-03-12', 'close_value': 61}, {'opportunity_id': 'AO9Z2D17', 'sales_agent': 'Violet Mclelland', 'product': 'GTX Plus Pro', 'account': 'Xx-zobam', 'deal_stage': 'Lost', 'engage_date': '2016-11-10', 'close_date': '2017-03-11', 'close_value': 0}, {'opportunity_id': '5M58DTJK', 'sales_agent': 'Elease Gluck', 'product': 'MG Special', 'account': 'Cheers', 'deal_stage': 'Won', 'engage_date': '2016-11-11', 'close_date': '2017-03-05', 'close_value': 58}, {'opportunity_id': 'KNY1OSAB', 'sales_agent': 'Maureen Marcano', 'product': 'GTXPro', 'account': 'Labdrill', 'deal_stage': 'Won', 'engage_date': '2016-11-11', 'close_date': '2017-03-14', 'close_value': 4899}, {'opportunity_id': 'EAZDUUM9', 'sales_agent': 'Rosie Papadopoulos', 'product': 'MG Advanced', 'account': 'Zotware', 'deal_stage': 'Lost', 'engage_date': '2016-11-11', 'close_date': '2017-03-01', 'close_value': 0}, {'opportunity_id': '2STUSOFE', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'dambase', 'deal_stage': 'Won', 'engage_date': '2016-11-11', 'close_date': '2017-03-03', 'close_value': 67}, {'opportunity_id': 'JYKM0B00', 'sales_agent': 'James Ascencio', 'product': 'GTXPro', 'account': 'Xx-holding', 'deal_stage': 'Won', 'engage_date': '2016-11-12', 'close_date': '2017-03-06', 'close_value': 4338}, {'opportunity_id': 'KU28360J', 'sales_agent': 'Kary Hendrixson', 'product': 'GTX Basic', 'account': 'Fasehatice', 'deal_stage': 'Won', 'engage_date': '2016-11-12', 'close_date': '2017-03-19', 'close_value': 578}, {'opportunity_id': 'N4SD17JR', 'sales_agent': 'Reed Clapper', 'product': 'GTX Basic', 'account': 'Acme Corporation', 'deal_stage': 'Won', 'engage_date': '2016-11-12', 'close_date': '2017-03-01', 'close_value': 556}, {'opportunity_id': 'E67P9Y3Q', 'sales_agent': 'Rosalina Dieter', 'product': 'GTX Basic', 'account': 'Green-Plus', 'deal_stage': 'Won', 'engage_date': '2016-11-12', 'close_date': '2017-03-03', 'close_value': 635}, {'opportunity_id': 'AT3MMVIS', 'sales_agent': 'Wilburn Farren', 'product': 'MG Advanced', 'account': 'The New York Inquirer', 'deal_stage': 'Won', 'engage_date': '2016-11-12', 'close_date': '2017-03-07', 'close_value': 3045}, {'opportunity_id': 'REJ11LRY', 'sales_agent': 'Garret Kinder', 'product': 'GTX Plus Basic', 'account': 'Mathtouch', 'deal_stage': 'Won', 'engage_date': '2016-11-13', 'close_date': '2017-03-14', 'close_value': 1233}, {'opportunity_id': 'ERV0CAZ7', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'Zumgoity', 'deal_stage': 'Won', 'engage_date': '2016-11-13', 'close_date': '2017-03-09', 'close_value': 60}, {'opportunity_id': '8SOQADK7', 'sales_agent': 'Anna Snelling', 'product': 'MG Special', 'account': 'Gogozoom', 'deal_stage': 'Lost', 'engage_date': '2016-11-14', 'close_date': '2017-03-30', 'close_value': 0}, {'opportunity_id': 'TCHFT25B', 'sales_agent': 'Darcel Schlecht', 'product': 'GTX Basic', 'account': 'Stanredtax', 'deal_stage': 'Lost', 'engage_date': '2016-11-14', 'close_date': '2017-03-08', 'close_value': 0}, {'opportunity_id': 'CZVN09WN', 'sales_agent': 'Darcel Schlecht', 'product': 'GTX Plus Basic', 'account': 'Konmatfix', 'deal_stage': 'Won', 'engage_date': '2016-11-14', 'close_date': '2017-03-20', 'close_value': 1170}, {'opportunity_id': 'EG7OFLFR', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Basic', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-14', 'close_date': '', 'close_value': ''}, {'opportunity_id': '30UQWUKB', 'sales_agent': 'Marty Freudenburg', 'product': 'GTX Plus Basic', 'account': 'Genco Pura Olive Oil Company', 'deal_stage': 'Won', 'engage_date': '2016-11-15', 'close_date': '2017-03-20', 'close_value': 1162}, {'opportunity_id': 'OLVI7L8M', 'sales_agent': 'Cassey Cress', 'product': 'GTXPro', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-16', 'close_date': '', 'close_value': ''}, {'opportunity_id': '97UN20YY', 'sales_agent': 'Darcel Schlecht', 'product': 'MG Advanced', 'account': 'Conecom', 'deal_stage': 'Won', 'engage_date': '2016-11-16', 'close_date': '2017-03-14', 'close_value': 3725}, {'opportunity_id': 'JXLERZ9O', 'sales_agent': 'Kary Hendrixson', 'product': 'GTX Basic', 'account': 'Golddex', 'deal_stage': 'Won', 'engage_date': '2016-11-16', 'close_date': '2017-03-31', 'close_value': 559}, {'opportunity_id': '6ROE69W5', 'sales_agent': 'Rosalina Dieter', 'product': 'GTX Basic', 'account': 'Plexzap', 'deal_stage': 'Lost', 'engage_date': '2016-11-16', 'close_date': '2017-03-11', 'close_value': 0}, {'opportunity_id': '0DFXFKT7', 'sales_agent': 'Darcel Schlecht', 'product': 'GTX Plus Basic', 'account': 'Rundofase', 'deal_stage': 'Lost', 'engage_date': '2016-11-17', 'close_date': '2017-03-21', 'close_value': 0}, {'opportunity_id': 'XKMZVSN4', 'sales_agent': 'James Ascencio', 'product': 'GTX Plus Pro', 'account': 'Sonron', 'deal_stage': 'Won', 'engage_date': '2016-11-17', 'close_date': '2017-03-05', 'close_value': 4667}, {'opportunity_id': 'IU8V0BZK', 'sales_agent': 'Marty Freudenburg', 'product': 'GTX Plus Basic', 'account': 'Finhigh', 'deal_stage': 'Won', 'engage_date': '2016-11-17', 'close_date': '2017-03-17', 'close_value': 903}, {'opportunity_id': 'XY42936P', 'sales_agent': 'Maureen Marcano', 'product': 'GTX Plus Basic', 'account': 'Finjob', 'deal_stage': 'Won', 'engage_date': '2016-11-17', 'close_date': '2017-03-13', 'close_value': 1180}, {'opportunity_id': 'XRN54MBM', 'sales_agent': 'Niesha Huffines', 'product': 'GTX Basic', 'account': 'Ron-tech', 'deal_stage': 'Won', 'engage_date': '2016-11-17', 'close_date': '2017-03-05', 'close_value': 487}, {'opportunity_id': '2V848WZD', 'sales_agent': 'Lajuana Vencill', 'product': 'MG Advanced', 'account': 'Stanredtax', 'deal_stage': 'Won', 'engage_date': '2016-11-18', 'close_date': '2017-03-04', 'close_value': 3180}, {'opportunity_id': 'ONYNTUCG', 'sales_agent': 'Darcel Schlecht', 'product': 'GTXPro', 'account': 'Funholding', 'deal_stage': 'Lost', 'engage_date': '2016-11-19', 'close_date': '2017-03-17', 'close_value': 0}, {'opportunity_id': 'HIOHX80Y', 'sales_agent': 'Darcel Schlecht', 'product': 'MG Advanced', 'account': 'Gogozoom', 'deal_stage': 'Won', 'engage_date': '2016-11-19', 'close_date': '2017-03-18', 'close_value': 3563}, {'opportunity_id': 'F5U1ACDD', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Plus Basic', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-19', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'LPKT07PV', 'sales_agent': 'Boris Faz', 'product': 'GTXPro', 'account': 'Opentech', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-23', 'close_value': 4704}, {'opportunity_id': 'WPB2SLIG', 'sales_agent': 'Donn Cantrell', 'product': 'GTX Plus Pro', 'account': 'Silis', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-14', 'close_value': 5585}, {'opportunity_id': 'XUSUEAV7', 'sales_agent': 'Elease Gluck', 'product': 'GTK 500', 'account': 'Zoomit', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-09', 'close_value': 25897}, {'opportunity_id': 'ZZY4516R', 'sales_agent': 'Hayden Neloms', 'product': 'MG Advanced', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-20', 'close_date': '', 'close_value': ''}, {'opportunity_id': '3TYPII47', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Plus Basic', 'account': 'Goodsilron', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-03', 'close_value': 1207}, {'opportunity_id': '7WAX8Z8O', 'sales_agent': 'Lajuana Vencill', 'product': 'MG Advanced', 'account': 'Cancity', 'deal_stage': 'Lost', 'engage_date': '2016-11-20', 'close_date': '2017-03-08', 'close_value': 0}, {'opportunity_id': 'MYDUMR3R', 'sales_agent': 'Lajuana Vencill', 'product': 'GTX Basic', 'account': 'Rangreen', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-04', 'close_value': 559}, {'opportunity_id': '0DRC1U9Q', 'sales_agent': 'Maureen Marcano', 'product': 'GTX Basic', 'account': 'Green-Plus', 'deal_stage': 'Engaging', 'engage_date': '2016-11-20', 'close_date': '', 'close_value': ''}, {'opportunity_id': '37JFKD4I', 'sales_agent': 'Niesha Huffines', 'product': 'GTX Plus Basic', 'account': 'dambase', 'deal_stage': 'Won', 'engage_date': '2016-11-20', 'close_date': '2017-03-09', 'close_value': 1033}, {'opportunity_id': '25YKPHX8', 'sales_agent': 'Donn Cantrell', 'product': 'GTX Basic', 'account': 'Kan-code', 'deal_stage': 'Won', 'engage_date': '2016-11-21', 'close_date': '2017-03-21', 'close_value': 462}, {'opportunity_id': 'BXXMA7F3', 'sales_agent': 'Hayden Neloms', 'product': 'MG Advanced', 'account': 'Nam-zim', 'deal_stage': 'Lost', 'engage_date': '2016-11-21', 'close_date': '2017-03-01', 'close_value': 0}, {'opportunity_id': 'GIUUTBXM', 'sales_agent': 'Kary Hendrixson', 'product': 'GTXPro', 'account': 'Y-corporation', 'deal_stage': 'Won', 'engage_date': '2016-11-21', 'close_date': '2017-03-14', 'close_value': 5539}, {'opportunity_id': 'MFX2LR1Q', 'sales_agent': 'Lajuana Vencill', 'product': 'MG Advanced', 'account': 'Ron-tech', 'deal_stage': 'Won', 'engage_date': '2016-11-21', 'close_date': '2017-03-15', 'close_value': 3573}, {'opportunity_id': 'DUHE9FLY', 'sales_agent': 'Marty Freudenburg', 'product': 'GTXPro', 'account': 'Conecom', 'deal_stage': 'Won', 'engage_date': '2016-11-21', 'close_date': '2017-03-01', 'close_value': 4926}, {'opportunity_id': '96BSG7R1', 'sales_agent': 'Zane Levy', 'product': 'GTX Plus Basic', 'account': 'Sunnamplex', 'deal_stage': 'Lost', 'engage_date': '2016-11-21', 'close_date': '2017-03-17', 'close_value': 0}, {'opportunity_id': '7FQMSWIX', 'sales_agent': 'Corliss Cosme', 'product': 'MG Special', 'account': 'Bioplex', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-04', 'close_value': 62}, {'opportunity_id': 'C20AVXN7', 'sales_agent': 'Darcel Schlecht', 'product': 'GTXPro', 'account': 'Gogozoom', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-14', 'close_value': 4359}, {'opportunity_id': 'GS1QVWCR', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Basic', 'account': 'Plusstrip', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-31', 'close_value': 566}, {'opportunity_id': 'ZWH8FXY3', 'sales_agent': 'Marty Freudenburg', 'product': 'GTX Basic', 'account': 'Toughzap', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-03', 'close_value': 508}, {'opportunity_id': '2U94Y3Q9', 'sales_agent': 'Rosie Papadopoulos', 'product': 'MG Advanced', 'account': 'Vehement Capital Partners', 'deal_stage': 'Lost', 'engage_date': '2016-11-22', 'close_date': '2017-03-20', 'close_value': 0}, {'opportunity_id': 'AAR79NOO', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'Codehow', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-11', 'close_value': 51}, {'opportunity_id': 'B6B0PNR2', 'sales_agent': 'Vicki Laflamme', 'product': 'GTXPro', 'account': 'Dalttechnology', 'deal_stage': 'Won', 'engage_date': '2016-11-22', 'close_date': '2017-03-05', 'close_value': 4899}, {'opportunity_id': 'M7I5O9YU', 'sales_agent': 'Corliss Cosme', 'product': 'GTX Basic', 'account': 'Cheers', 'deal_stage': 'Engaging', 'engage_date': '2016-11-23', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'LXZA2OSZ', 'sales_agent': 'Corliss Cosme', 'product': 'GTX Plus Pro', 'account': 'Ontomedia', 'deal_stage': 'Won', 'engage_date': '2016-11-23', 'close_date': '2017-03-03', 'close_value': 5790}, {'opportunity_id': 'N0ONCYVZ', 'sales_agent': 'Donn Cantrell', 'product': 'MG Special', 'account': 'Kinnamplus', 'deal_stage': 'Lost', 'engage_date': '2016-11-23', 'close_date': '2017-03-30', 'close_value': 0}, {'opportunity_id': 'GYB4W2AU', 'sales_agent': 'Elease Gluck', 'product': 'MG Advanced', 'account': '', 'deal_stage': 'Engaging', 'engage_date': '2016-11-23', 'close_date': '', 'close_value': ''}, {'opportunity_id': '513DPFX5', 'sales_agent': 'Gladys Colclough', 'product': 'GTXPro', 'account': 'Codehow', 'deal_stage': 'Won', 'engage_date': '2016-11-23', 'close_date': '2017-03-03', 'close_value': 4438}, {'opportunity_id': 'RU023K5W', 'sales_agent': 'Gladys Colclough', 'product': 'MG Advanced', 'account': 'Finhigh', 'deal_stage': 'Won', 'engage_date': '2016-11-23', 'close_date': '2017-03-17', 'close_value': 2972}, {'opportunity_id': 'VDIU10RV', 'sales_agent': 'Markita Hansen', 'product': 'MG Special', 'account': 'Lexiqvolax', 'deal_stage': 'Engaging', 'engage_date': '2016-11-23', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'BZCBQ514', 'sales_agent': 'Markita Hansen', 'product': 'GTX Basic', 'account': 'Y-corporation', 'deal_stage': 'Won', 'engage_date': '2016-11-23', 'close_date': '2017-03-01', 'close_value': 523}, {'opportunity_id': 'HEE6P0QH', 'sales_agent': 'Anna Snelling', 'product': 'MG Advanced', 'account': 'Statholdings', 'deal_stage': 'Won', 'engage_date': '2016-11-24', 'close_date': '2017-03-25', 'close_value': 3647}, {'opportunity_id': 'L8CHRJ2B', 'sales_agent': 'Cassey Cress', 'product': 'MG Advanced', 'account': 'Umbrella Corporation', 'deal_stage': 'Won', 'engage_date': '2016-11-24', 'close_date': '2017-03-01', 'close_value': 4200}, {'opportunity_id': '579LZ3F9', 'sales_agent': 'Daniell Hammack', 'product': 'GTX Plus Basic', 'account': 'J-Texon', 'deal_stage': 'Engaging', 'engage_date': '2016-11-24', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'SU8JNMP4', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Plus Basic', 'account': 'Bubba Gump', 'deal_stage': 'Engaging', 'engage_date': '2016-11-24', 'close_date': '', 'close_value': ''}, {'opportunity_id': 'V2X2KMUR', 'sales_agent': 'Kami Bicknell', 'product': 'GTX Plus Basic', 'account': 'Faxquote', 'deal_stage': 'Won', 'engage_date': '2016-11-24', 'close_date': '2017-03-28', 'close_value': 1059}, {'opportunity_id': 'AJIPJP75', 'sales_agent': 'Marty Freudenburg', 'product': 'GTX Plus Basic', 'account': 'Codehow', 'deal_stage': 'Lost', 'engage_date': '2016-11-24', 'close_date': '2017-03-05', 'close_value': 0}, {'opportunity_id': 'NYVA2G6U', 'sales_agent': 'Versie Hillebrand', 'product': 'MG Special', 'account': 'Dontechi', 'deal_stage': 'Won', 'engage_date': '2016-11-24', 'close_date': '2017-03-02', 'close_value': 57}, {'opportunity_id': 'FF45BXTL', 'sales_agent': 'Vicki Laflamme', 'product': 'MG Advanced', 'account': 'Konex', 'de

In [6]:
import pandas as pd

In [17]:
df=pd.DataFrame(data)
df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517
...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,,Prospecting,,,
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,,Prospecting,,,
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,,Prospecting,,,
8798,18IUIUK0,Versie Hillebrand,MG Advanced,,Prospecting,,,
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,,Prospecting,,,

In [9]:
from google.oauth2.service_account import Credentials

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds = Credentials.from_service_account_file("b2b-sales-488816-f00097d78156.json", scopes=scope)
client = gspread.authorize(creds)

sheet = client.open("accounts").sheet1
data2 = sheet.get_all_records()
print(data2)

[{'account': 'Acme Corporation', 'sector': 'technolgy', 'year_established': 1996, 'revenue': 1100.04, 'employees': 2822, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Betasoloin', 'sector': 'medical', 'year_established': 1999, 'revenue': 251.41, 'employees': 495, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Betatech', 'sector': 'medical', 'year_established': 1986, 'revenue': 647.18, 'employees': 1185, 'office_location': 'Kenya', 'subsidiary_of': ''}, {'account': 'Bioholding', 'sector': 'medical', 'year_established': 2012, 'revenue': 587.34, 'employees': 1356, 'office_location': 'Philipines', 'subsidiary_of': ''}, {'account': 'Bioplex', 'sector': 'medical', 'year_established': 1991, 'revenue': 326.82, 'employees': 1016, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Blackzim', 'sector': 'retail', 'year_established': 2009, 'revenue': 497.11, 'employees': 1588, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Bluth Company', 'sector': 'technolgy', 'year_established': 1993, 'revenue': 1242.32, 'employees': 3027, 'office_location': 'United States', 'subsidiary_of': 'Acme Corporation'}, {'account': 'Bubba Gump', 'sector': 'software', 'year_established': 2002, 'revenue': 987.39, 'employees': 2253, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Cancity', 'sector': 'retail', 'year_established': 2001, 'revenue': 718.62, 'employees': 2448, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Cheers', 'sector': 'entertainment', 'year_established': 1993, 'revenue': 4269.9, 'employees': 6472, 'office_location': 'United States', 'subsidiary_of': 'Massive Dynamic'}, {'account': 'Codehow', 'sector': 'software', 'year_established': 1998, 'revenue': 2714.9, 'employees': 2641, 'office_location': 'United States', 'subsidiary_of': 'Acme Corporation'}, {'account': 'Condax', 'sector': 'medical', 'year_established': 2017, 'revenue': 4.54, 'employees': 9, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Conecom', 'sector': 'technolgy', 'year_established': 2005, 'revenue': 1520.66, 'employees': 1806, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Dalttechnology', 'sector': 'software', 'year_established': 2013, 'revenue': 98.79, 'employees': 96, 'office_location': 'United States', 'subsidiary_of': 'Bubba Gump'}, {'account': 'dambase', 'sector': 'marketing', 'year_established': 1995, 'revenue': 2173.98, 'employees': 2928, 'office_location': 'United States', 'subsidiary_of': 'Inity'}, {'account': 'Domzoom', 'sector': 'entertainment', 'year_established': 1998, 'revenue': 217.87, 'employees': 551, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Doncon', 'sector': 'technolgy', 'year_established': 2010, 'revenue': 587.72, 'employees': 1501, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Donquadtech', 'sector': 'technolgy', 'year_established': 1992, 'revenue': 1712.68, 'employees': 3194, 'office_location': 'United States', 'subsidiary_of': 'Acme Corporation'}, {'account': 'Dontechi', 'sector': 'software', 'year_established': 1982, 'revenue': 4618, 'employees': 10083, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Donware', 'sector': 'marketing', 'year_established': 1999, 'revenue': 1197.44, 'employees': 2570, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Fasehatice', 'sector': 'retail', 'year_established': 1990, 'revenue': 4968.91, 'employees': 7523, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Faxquote', 'sector': 'telecommunications', 'year_established': 1995, 'revenue': 1825.82, 'employees': 5595, 'office_location': 'United States', 'subsidiary_of': 'Sonron'}, {'account': 'Finhigh', 'sector': 'finance', 'year_established': 2006, 'revenue': 1102.43, 'employees': 1759, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Finjob', 'sector': 'employment', 'year_established': 1988, 'revenue': 2059.9, 'employees': 3644, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Funholding', 'sector': 'finance', 'year_established': 1991, 'revenue': 2819.5, 'employees': 7227, 'office_location': 'United States', 'subsidiary_of': 'Golddex'}, {'account': 'Ganjaflex', 'sector': 'retail', 'year_established': 1995, 'revenue': 5158.71, 'employees': 17479, 'office_location': 'Japan', 'subsidiary_of': ''}, {'account': 'Gekko & Co', 'sector': 'retail', 'year_established': 1990, 'revenue': 2520.83, 'employees': 3502, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Genco Pura Olive Oil Company', 'sector': 'retail', 'year_established': 2007, 'revenue': 894.33, 'employees': 1635, 'office_location': 'Italy', 'subsidiary_of': ''}, {'account': 'Globex Corporation', 'sector': 'technolgy', 'year_established': 2000, 'revenue': 1223.72, 'employees': 2497, 'office_location': 'Norway', 'subsidiary_of': ''}, {'account': 'Gogozoom', 'sector': 'telecommunications', 'year_established': 2007, 'revenue': 86.68, 'employees': 187, 'office_location': 'United States', 'subsidiary_of': 'Sonron'}, {'account': 'Golddex', 'sector': 'finance', 'year_established': 2008, 'revenue': 52.5, 'employees': 165, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Goodsilron', 'sector': 'marketing', 'year_established': 2000, 'revenue': 2952.73, 'employees': 5107, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Green-Plus', 'sector': 'services', 'year_established': 2003, 'revenue': 692.19, 'employees': 1922, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Groovestreet', 'sector': 'retail', 'year_established': 2003, 'revenue': 223.8, 'employees': 299, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Hatfan', 'sector': 'services', 'year_established': 1982, 'revenue': 792.46, 'employees': 1299, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Hottechi', 'sector': 'technolgy', 'year_established': 1997, 'revenue': 8170.38, 'employees': 16499, 'office_location': 'Korea', 'subsidiary_of': ''}, {'account': 'Initech', 'sector': 'telecommunications', 'year_established': 1994, 'revenue': 6395.05, 'employees': 20275, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Inity', 'sector': 'marketing', 'year_established': 1986, 'revenue': 2403.58, 'employees': 8801, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Isdom', 'sector': 'medical', 'year_established': 2002, 'revenue': 3178.24, 'employees': 4540, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Iselectrics', 'sector': 'technolgy', 'year_established': 2011, 'revenue': 527.11, 'employees': 1428, 'office_location': 'United States', 'subsidiary_of': 'Acme Corporation'}, {'account': 'J-Texon', 'sector': 'retail', 'year_established': 1989, 'revenue': 1388.67, 'employees': 3583, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Kan-code', 'sector': 'software', 'year_established': 1982, 'revenue': 11698.03, 'employees': 34288, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Kinnamplus', 'sector': 'retail', 'year_established': 2004, 'revenue': 702.72, 'employees': 1831, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Konex', 'sector': 'technolgy', 'year_established': 1980, 'revenue': 7708.38, 'employees': 13756, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Konmatfix', 'sector': 'marketing', 'year_established': 1985, 'revenue': 375.43, 'employees': 1190, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Labdrill', 'sector': 'medical', 'year_established': 1985, 'revenue': 2741.37, 'employees': 9226, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Lexiqvolax', 'sector': 'medical', 'year_established': 2004, 'revenue': 1618.89, 'employees': 3889, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Massive Dynamic', 'sector': 'entertainment', 'year_established': 1989, 'revenue': 665.06, 'employees': 1095, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Mathtouch', 'sector': 'marketing', 'year_established': 1984, 'revenue': 3027.46, 'employees': 9516, 'office_location': 'Jordan', 'subsidiary_of': ''}, {'account': 'Nam-zim', 'sector': 'services', 'year_established': 1987, 'revenue': 405.59, 'employees': 1179, 'office_location': 'Brazil', 'subsidiary_of': 'Warephase'}, {'account': 'Newex', 'sector': 'services', 'year_established': 1991, 'revenue': 1012.72, 'employees': 3492, 'office_location': 'Germany', 'subsidiary_of': ''}, {'account': 'Ontomedia', 'sector': 'employment', 'year_established': 1997, 'revenue': 882.12, 'employees': 2769, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Opentech', 'sector': 'finance', 'year_established': 1994, 'revenue': 355.23, 'employees': 853, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Plexzap', 'sector': 'retail', 'year_established': 2001, 'revenue': 2437.85, 'employees': 4874, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Plusstrip', 'sector': 'entertainment', 'year_established': 2002, 'revenue': 349.81, 'employees': 315, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Plussunin', 'sector': 'retail', 'year_established': 2003, 'revenue': 1419.98, 'employees': 4018, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Rangreen', 'sector': 'technolgy', 'year_established': 1987, 'revenue': 2938.67, 'employees': 8775, 'office_location': 'Panama', 'subsidiary_of': ''}, {'account': 'Rantouch', 'sector': 'telecommunications', 'year_established': 1994, 'revenue': 1188.42, 'employees': 3015, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Ron-tech', 'sector': 'medical', 'year_established': 1992, 'revenue': 3922.42, 'employees': 6837, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Rundofase', 'sector': 'technolgy', 'year_established': 1983, 'revenue': 1008.06, 'employees': 1238, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Scotfind', 'sector': 'software', 'year_established': 1996, 'revenue': 6354.87, 'employees': 16780, 'office_location': 'United States', 'subsidiary_of': 'Bubba Gump'}, {'account': 'Scottech', 'sector': 'marketing', 'year_established': 2012, 'revenue': 45.39, 'employees': 100, 'office_location': 'United States', 'subsidiary_of': 'Inity'}, {'account': 'Silis', 'sector': 'medical', 'year_established': 1994, 'revenue': 2818.38, 'employees': 6290, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Singletechno', 'sector': 'retail', 'year_established': 1996, 'revenue': 2214.94, 'employees': 5374, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Sonron', 'sector': 'telecommunications', 'year_established': 1999, 'revenue': 1699.85, 'employees': 5108, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Stanredtax', 'sector': 'finance', 'year_established': 1987, 'revenue': 1698.2, 'employees': 3798, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Statholdings', 'sector': 'employment', 'year_established': 1997, 'revenue': 291.27, 'employees': 586, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Streethex', 'sector': 'retail', 'year_established': 1988, 'revenue': 1376.8, 'employees': 1165, 'office_location': 'Belgium', 'subsidiary_of': ''}, {'account': 'Sumace', 'sector': 'retail', 'year_established': 2000, 'revenue': 167.89, 'employees': 493, 'office_location': 'Romania', 'subsidiary_of': ''}, {'account': 'Sunnamplex', 'sector': 'marketing', 'year_established': 2008, 'revenue': 894.37, 'employees': 1593, 'office_location': 'Poland', 'subsidiary_of': ''}, {'account': 'The New York Inquirer', 'sector': 'medical', 'year_established': 1996, 'revenue': 439.21, 'employees': 792, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Toughzap', 'sector': 'retail', 'year_established': 1995, 'revenue': 332.43, 'employees': 799, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Treequote', 'sector': 'telecommunications', 'year_established': 1988, 'revenue': 5266.09, 'employees': 8595, 'office_location': 'United States', 'subsidiary_of': 'Sonron'}, {'account': 'Umbrella Corporation', 'sector': 'finance', 'year_established': 1998, 'revenue': 2022.14, 'employees': 5113, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Vehement Capital Partners', 'sector': 'finance', 'year_established': 1993, 'revenue': 646.1, 'employees': 883, 'office_location': 'United States', 'subsidiary_of': 'Golddex'}, {'account': 'Warephase', 'sector': 'services', 'year_established': 1997, 'revenue': 2041.73, 'employees': 5276, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Xx-holding', 'sector': 'finance', 'year_established': 1993, 'revenue': 7537.24, 'employees': 20293, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Xx-zobam', 'sector': 'entertainment', 'year_established': 1989, 'revenue': 3838.39, 'employees': 8274, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Y-corporation', 'sector': 'employment', 'year_established': 1983, 'revenue': 2871.35, 'employees': 9561, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Yearin', 'sector': 'retail', 'year_established': 2005, 'revenue': 2261.05, 'employees': 3851, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Zathunicon', 'sector': 'retail', 'year_established': 2010, 'revenue': 71.12, 'employees': 144, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Zencorporation', 'sector': 'technolgy', 'year_established': 2011, 'revenue': 40.79, 'employees': 142, 'office_location': 'China', 'subsidiary_of': ''}, {'account': 'Zoomit', 'sector': 'entertainment', 'year_established': 1992, 'revenue': 324.19, 'employees': 978, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Zotware', 'sector': 'software', 'year_established': 1979, 'revenue': 4478.47, 'employees': 13809, 'office_location': 'United States', 'subsidiary_of': ''}, {'account': 'Zumgoity', 'sector': 'medical', 'year_established': 1984, 'revenue': 441.08, 'employees': 1210, 'office_location': 'United States', 'subsidiary_of': ''}]

In [10]:
df2=pd.DataFrame(data2)
df2

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,
1,Betasoloin,medical,1999,251.41,495,United States,
2,Betatech,medical,1986,647.18,1185,Kenya,
3,Bioholding,medical,2012,587.34,1356,Philipines,
4,Bioplex,medical,1991,326.82,1016,United States,
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,
81,Zencorporation,technolgy,2011,40.79,142,China,
82,Zoomit,entertainment,1992,324.19,978,United States,
83,Zotware,software,1979,4478.47,13809,United States,
84,Zumgoity,medical,1984,441.08,1210,United States,

In [11]:
from google.oauth2.service_account import Credentials

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds = Credentials.from_service_account_file("b2b-sales-488816-f00097d78156.json", scopes=scope)
client = gspread.authorize(creds)

sheet = client.open("products").sheet1
data3 = sheet.get_all_records()
print(data3)

[{'product': 'GTX Basic', 'series': 'GTX', 'sales_price': 550}, {'product': 'GTX Pro', 'series': 'GTX', 'sales_price': 4821}, {'product': 'MG Special', 'series': 'MG', 'sales_price': 55}, {'product': 'MG Advanced', 'series': 'MG', 'sales_price': 3393}, {'product': 'GTX Plus Pro', 'series': 'GTX', 'sales_price': 5482}, {'product': 'GTX Plus Basic', 'series': 'GTX', 'sales_price': 1096}, {'product': 'GTK 500', 'series': 'GTK', 'sales_price': 26768}]

In [12]:
df3=pd.DataFrame(data3)
df3

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

In [13]:
from google.oauth2.service_account import Credentials

scope = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds = Credentials.from_service_account_file("b2b-sales-488816-f00097d78156.json", scopes=scope)
client = gspread.authorize(creds)

sheet = client.open("sales_teams").sheet1
data4 = sheet.get_all_records()
print(data4)

[{'sales_agent': 'Anna Snelling', 'manager': 'Dustin Brinkmann', 'regional_office': 'Central'}, {'sales_agent': 'Cecily Lampkin', 'manager': 'Dustin Brinkmann', 'regional_office': 'Central'}, {'sales_agent': 'Versie Hillebrand', 'manager': 'Dustin Brinkmann', 'regional_office': 'Central'}, {'sales_agent': 'Lajuana Vencill', 'manager': 'Dustin Brinkmann', 'regional_office': 'Central'}, {'sales_agent': 'Moses Frase', 'manager': 'Dustin Brinkmann', 'regional_office': 'Central'}, {'sales_agent': 'Jonathan Berthelot', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Marty Freudenburg', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Gladys Colclough', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Niesha Huffines', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Darcel Schlecht', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Mei-Mei Johns', 'manager': 'Melvin Marxen', 'regional_office': 'Central'}, {'sales_agent': 'Violet Mclelland', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Corliss Cosme', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Rosie Papadopoulos', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Garret Kinder', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Wilburn Farren', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Elizabeth Anderson', 'manager': 'Cara Losch', 'regional_office': 'East'}, {'sales_agent': 'Daniell Hammack', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Cassey Cress', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Donn Cantrell', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Reed Clapper', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Boris Faz', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Natalya Ivanova', 'manager': 'Rocco Neubert', 'regional_office': 'East'}, {'sales_agent': 'Vicki Laflamme', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'Rosalina Dieter', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'Hayden Neloms', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'Markita Hansen', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'Elease Gluck', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'Carol Thompson', 'manager': 'Celia Rouche', 'regional_office': 'West'}, {'sales_agent': 'James Ascencio', 'manager': 'Summer Sewald', 'regional_office': 'West'}, {'sales_agent': 'Kary Hendrixson', 'manager': 'Summer Sewald', 'regional_office': 'West'}, {'sales_agent': 'Kami Bicknell', 'manager': 'Summer Sewald', 'regional_office': 'West'}, {'sales_agent': 'Zane Levy', 'manager': 'Summer Sewald', 'regional_office': 'West'}, {'sales_agent': 'Maureen Marcano', 'manager': 'Summer Sewald', 'regional_office': 'West'}, {'sales_agent': 'Carl Lin', 'manager': 'Summer Sewald', 'regional_office': 'West'}]

In [14]:
df4=pd.DataFrame(data4)
df4

           sales_agent           manager regional_office
0        Anna Snelling  Dustin Brinkmann         Central
1       Cecily Lampkin  Dustin Brinkmann         Central
2    Versie Hillebrand  Dustin Brinkmann         Central
3      Lajuana Vencill  Dustin Brinkmann         Central
4          Moses Frase  Dustin Brinkmann         Central
5   Jonathan Berthelot     Melvin Marxen         Central
6    Marty Freudenburg     Melvin Marxen         Central
7     Gladys Colclough     Melvin Marxen         Central
8      Niesha Huffines     Melvin Marxen         Central
9      Darcel Schlecht     Melvin Marxen         Central
10       Mei-Mei Johns     Melvin Marxen         Central
11    Violet Mclelland        Cara Losch            East
12       Corliss Cosme        Cara Losch            East
13  Rosie Papadopoulos        Cara Losch            East
14       Garret Kinder        Cara Losch            East
15      Wilburn Farren        Cara Losch            East
16  Elizabeth Anderson        Cara Losch            East
17     Daniell Hammack     Rocco Neubert            East
18        Cassey Cress     Rocco Neubert            East
19       Donn Cantrell     Rocco Neubert            East
20        Reed Clapper     Rocco Neubert            East
21           Boris Faz     Rocco Neubert            East
22     Natalya Ivanova     Rocco Neubert            East
23      Vicki Laflamme      Celia Rouche            West
24     Rosalina Dieter      Celia Rouche            West
25       Hayden Neloms      Celia Rouche            West
26      Markita Hansen      Celia Rouche            West
27        Elease Gluck      Celia Rouche            West
28      Carol Thompson      Celia Rouche            West
29      James Ascencio     Summer Sewald            West
30     Kary Hendrixson     Summer Sewald            West
31       Kami Bicknell     Summer Sewald            West
32           Zane Levy     Summer Sewald            West
33     Maureen Marcano     Summer Sewald            West
34            Carl Lin     Summer Sewald            West

In [19]:
import pandas as pd

salespipeline = pd.DataFrame(data)
accounts = pd.DataFrame(data2)
products = pd.DataFrame(data3)
salesteam = pd.DataFrame(data4)

print("All datasets loaded successfully ✅")

All datasets loaded successfully ✅

In [21]:
df1 =salespipeline.head()
df1

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517

In [24]:
df2 = accounts
df2

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,
1,Betasoloin,medical,1999,251.41,495,United States,
2,Betatech,medical,1986,647.18,1185,Kenya,
3,Bioholding,medical,2012,587.34,1356,Philipines,
4,Bioplex,medical,1991,326.82,1016,United States,
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,
81,Zencorporation,technolgy,2011,40.79,142,China,
82,Zoomit,entertainment,1992,324.19,978,United States,
83,Zotware,software,1979,4478.47,13809,United States,
84,Zumgoity,medical,1984,441.08,1210,United States,

In [25]:
df3 =products 
df3

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

In [26]:
df4 =salesteam
df4

           sales_agent           manager regional_office
0        Anna Snelling  Dustin Brinkmann         Central
1       Cecily Lampkin  Dustin Brinkmann         Central
2    Versie Hillebrand  Dustin Brinkmann         Central
3      Lajuana Vencill  Dustin Brinkmann         Central
4          Moses Frase  Dustin Brinkmann         Central
5   Jonathan Berthelot     Melvin Marxen         Central
6    Marty Freudenburg     Melvin Marxen         Central
7     Gladys Colclough     Melvin Marxen         Central
8      Niesha Huffines     Melvin Marxen         Central
9      Darcel Schlecht     Melvin Marxen         Central
10       Mei-Mei Johns     Melvin Marxen         Central
11    Violet Mclelland        Cara Losch            East
12       Corliss Cosme        Cara Losch            East
13  Rosie Papadopoulos        Cara Losch            East
14       Garret Kinder        Cara Losch            East
15      Wilburn Farren        Cara Losch            East
16  Elizabeth Anderson        Cara Losch            East
17     Daniell Hammack     Rocco Neubert            East
18        Cassey Cress     Rocco Neubert            East
19       Donn Cantrell     Rocco Neubert            East
20        Reed Clapper     Rocco Neubert            East
21           Boris Faz     Rocco Neubert            East
22     Natalya Ivanova     Rocco Neubert            East
23      Vicki Laflamme      Celia Rouche            West
24     Rosalina Dieter      Celia Rouche            West
25       Hayden Neloms      Celia Rouche            West
26      Markita Hansen      Celia Rouche            West
27        Elease Gluck      Celia Rouche            West
28      Carol Thompson      Celia Rouche            West
29      James Ascencio     Summer Sewald            West
30     Kary Hendrixson     Summer Sewald            West
31       Kami Bicknell     Summer Sewald            West
32           Zane Levy     Summer Sewald            West
33     Maureen Marcano     Summer Sewald            West
34            Carl Lin     Summer Sewald            West

### IMPORTING IMPORTANT LIB

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### merged dataset

In [32]:
merged_df = df1.merge(df2, on='account', how='left') \
               .merge(df3, on='product', how='left') \
               .merge(df4, on='sales_agent', how='left')
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,718.62,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,3178.24,4540,United States,,NaN,NaN,Melvin Marxen,Central
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,718.62,2448,United States,,MG,55.0,Melvin Marxen,Central
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,2714.90,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,792.46,1299,United States,,GTX,550.0,Summer Sewald,West

#### data cleaning

In [28]:
merged_df.info()
merged_df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   opportunity_id    8800 non-null   object
 1   sales_agent       8800 non-null   object
 2   product           8800 non-null   object
 3   account           8800 non-null   object
 4   deal_stage        8800 non-null   object
 5   engage_date       8800 non-null   object
 6   close_date        8800 non-null   object
 7   close_value       8800 non-null   object
 8   sector            7375 non-null   object
 9   year_established  7375 non-null   float64
 10  revenue           7375 non-null   float64
 11  employees         7375 non-null   float64
 12  office_location   7375 non-null   object
 13  subsidiary_of     7375 non-null   object
 14  series            7320 non-null   object
 15  sales_price       7320 non-null   float64
 16  manager           8800 non-null   object
 17  regional_office   8800 non-null   object
dtypes: float64(4), object(14)
memory usage: 1.2+ MB

(8800, 18)

In [29]:
merged_df.isnull().sum()

opportunity_id         0
sales_agent            0
product                0
account                0
deal_stage             0
engage_date            0
close_date             0
close_value            0
sector              1425
year_established    1425
revenue             1425
employees           1425
office_location     1425
subsidiary_of       1425
series              1480
sales_price         1480
manager                0
regional_office        0
dtype: int64

### PHASE 1 — Business Objective (Write in Project)

Analyze sales pipeline data to identify revenue drivers, sales performance patterns, sector contribution, conversion efficiency, and regional trends to improve business growth strategy.

### PHASE 2 — Feature Engineering

#### Convert Dates
#converting the column from string (text) to datetime format

In [33]:
merged_df['engage_date'] = pd.to_datetime(merged_df['engage_date'])
merged_df['close_date'] = pd.to_datetime(merged_df['close_date'])
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,718.62,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,3178.24,4540,United States,,NaN,NaN,Melvin Marxen,Central
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,718.62,2448,United States,,MG,55.0,Melvin Marxen,Central
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,2714.90,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,792.46,1299,United States,,GTX,550.0,Summer Sewald,West

#### total revenue

In [34]:
merged_df['revenue'] = merged_df['close_value'].sum()

In [35]:
merged_df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,6723,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,6723,4540,United States,,NaN,NaN,Melvin Marxen,Central
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,6723,2448,United States,,MG,55.0,Melvin Marxen,Central
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,6723,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,6723,1299,United States,,GTX,550.0,Summer Sewald,West

#### We get a numeric column to calculate conversion rate easily

In [75]:
import numpy as np

merged_df['deal_won_flag'] = np.where(merged_df['deal_stage'] == 'Won', 1, 0)
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office,closing_days,close_year,close_month,revenue_per_employee,deal_won_flag
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0,retail,2001.0,718.62,2448.0,United States,,GTX,1096.0,Dustin Brinkmann,Central,132.0,2017.0,3.0,0.293554,1
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0,medical,2002.0,3178.24,4540.0,United States,,NaN,NaN,Melvin Marxen,Central,137.0,2017.0,3.0,0.700053,1
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0,retail,2001.0,718.62,2448.0,United States,,MG,55.0,Melvin Marxen,Central,133.0,2017.0,3.0,0.293554,1
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0,software,1998.0,2714.90,2641.0,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central,135.0,2017.0,3.0,1.027982,1
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0,services,1982.0,792.46,1299.0,United States,,GTX,550.0,Summer Sewald,West,128.0,2017.0,3.0,0.610054,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN,NaN,0
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN,NaN,0
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN,NaN,0
8798,18IUIUK0,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN,NaN,0
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN,NaN,0

#### Create Closing Days
To measure how long each deal takes to close.

In [36]:
merged_df['closing_days'] = (merged_df['close_date'] - merged_df['engage_date']).dt.days
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office,closing_days
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,6723,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central,132
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,6723,4540,United States,,NaN,NaN,Melvin Marxen,Central,137
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,6723,2448,United States,,MG,55.0,Melvin Marxen,Central,133
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,6723,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central,135
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,6723,1299,United States,,GTX,550.0,Summer Sewald,West,128

#### Extract Year & Month
checking sales trends over time.

In [39]:
merged_df['close_year'] = merged_df['close_date'].dt.year
merged_df['close_month'] = merged_df['close_date'].dt.month
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,...,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office,closing_days,close_year,close_month
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001.0,...,2448.0,United States,,GTX,1096.0,Dustin Brinkmann,Central,132.0,2017.0,3.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002.0,...,4540.0,United States,,NaN,NaN,Melvin Marxen,Central,137.0,2017.0,3.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001.0,...,2448.0,United States,,MG,55.0,Melvin Marxen,Central,133.0,2017.0,3.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998.0,...,2641.0,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central,135.0,2017.0,3.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982.0,...,1299.0,United States,,GTX,550.0,Summer Sewald,West,128.0,2017.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,,NaN,NaN,...,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,,NaN,NaN,...,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,,NaN,NaN,...,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN
8798,18IUIUK0,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,,NaN,NaN,...,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,,Prospecting,NaT,NaT,,NaN,NaN,...,NaN,NaN,NaN,MG,3393.0,Dustin Brinkmann,Central,NaN,NaN,NaN

#### Revenue Per Employee
which employee genrated more revenue

In [41]:
merged_df['revenue_per_employee'] = merged_df['revenue'] / merged_df['employees']
merged_df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office,closing_days,revenue_per_employee
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,6723,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central,132,2.746324
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,6723,4540,United States,,NaN,NaN,Melvin Marxen,Central,137,1.480837
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,6723,2448,United States,,MG,55.0,Melvin Marxen,Central,133,2.746324
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,6723,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central,135,2.545627
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,6723,1299,United States,,GTX,550.0,Summer Sewald,West,128,5.175520

##### to see max column in my dataset

In [40]:
pd.set_option('display.max_columns', None)
merged_df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,series,sales_price,manager,regional_office,closing_days
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054,retail,2001,6723,2448,United States,,GTX,1096.0,Dustin Brinkmann,Central,132
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514,medical,2002,6723,4540,United States,,NaN,NaN,Melvin Marxen,Central,137
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50,retail,2001,6723,2448,United States,,MG,55.0,Melvin Marxen,Central,133
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588,software,1998,6723,2641,United States,Acme Corporation,GTX,550.0,Dustin Brinkmann,Central,135
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517,services,1982,6723,1299,United States,,GTX,550.0,Summer Sewald,West,128

## PHASE 3 —  Revenue Analysis

##### Total Revenue

In [46]:
merged_df['close_value'] = pd.to_numeric(merged_df['close_value'], errors='coerce')

In [50]:
#its treating the close value as the string so we converting it into the float value

In [47]:
merged_df['close_value'].fillna(0, inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_13660\848520858.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['close_value'].fillna(0, inplace=True)

In [42]:
revenue = merged_df['close_value'].sum()
print(revenue)

6723

In [49]:
merged_df['close_value'].dtype

dtype('float64')

#### product vise revenue

In [60]:
merged_df.groupby("product")["close_value"].sum().reset_index().sort_values(by="close_value",ascending = False)

          product  close_value
4          GTXPro    3510578.0
3    GTX Plus Pro    2629651.0
5     MG Advanced    2216387.0
2  GTX Plus Basic     705275.0
1       GTX Basic     499263.0
0         GTK 500     400612.0
6      MG Special      43768.0

#### Revenue by Sector

In [63]:
merged_df.groupby('sector')['close_value'].sum().reset_index().sort_values(by ='close_value', ascending=False)

               sector  close_value
5              retail    1867528.0
8           technolgy    1515487.0
4             medical    1359595.0
7            software    1077934.0
2             finance     950908.0
3           marketing     922321.0
1       entertainment     689007.0
9  telecommunications     653574.0
6            services     533006.0
0          employment     436174.0

#### Revenue by Sales Agent

In [68]:
merged_df.groupby("sales_agent")["close_value"].sum().reset_index().sort_values(by ="close_value",ascending=False).head(10)

        sales_agent  close_value
6   Darcel Schlecht    1153214.0
26   Vicki Laflamme     478396.0
15  Kary Hendrixson     454298.0
2      Cassey Cress     450489.0
7     Donn Cantrell     445860.0
22     Reed Clapper     438336.0
29        Zane Levy     430068.0
4     Corliss Cosme     421036.0
12   James Ascencio     413533.0
5   Daniell Hammack     364229.0

#### Revenue by Region

In [72]:
merged_df.groupby('regional_office')['close_value'].sum().reset_index().sort_values(by = "close_value",ascending=False)

  regional_office  close_value
2            West    3568647.0
0         Central    3346293.0
1            East    3090594.0

# PART 4 — Sales Analysis

#### Conversion Rate
To measure percentage of deals successfully closed.

In [77]:
n = merged_df['deal_won_flag'].mean()
print(n)

0.48159090909090907

##### dentify who closes deals most efficiently

In [80]:
merged_df.groupby('sales_agent')['deal_won_flag'].mean().reset_index().sort_values(by = "sales_agent",ascending=False)

           sales_agent  deal_won_flag
29           Zane Levy       0.461318
28      Wilburn Farren       0.500000
27    Violet Mclelland       0.467433
26      Vicki Laflamme       0.490022
25   Versie Hillebrand       0.487535
24  Rosie Papadopoulos       0.487500
23     Rosalina Dieter       0.450000
22        Reed Clapper       0.654008
21     Niesha Huffines       0.439331
20         Moses Frase       0.496154
19     Maureen Marcano       0.522807
18   Marty Freudenburg       0.434164
17      Markita Hansen       0.424837
16     Lajuana Vencill       0.408360
15     Kary Hendrixson       0.477169
14       Kami Bicknell       0.480663
13  Jonathan Berthelot       0.495652
12      James Ascencio       0.505618
11       Hayden Neloms       0.529703
10    Gladys Colclough       0.425868
9        Garret Kinder       0.609756
8         Elease Gluck       0.451977
7        Donn Cantrell       0.574545
6      Darcel Schlecht       0.467202
5      Daniell Hammack       0.440154
4        Corliss Cosme       0.483871
3       Cecily Lampkin       0.527094
2         Cassey Cress       0.471098
1            Boris Faz       0.480952
0        Anna Snelling       0.464286

## PHASE 5 — Time & Performance Analysis

##### Monthly Revenue Trend
to show all 12 months

In [89]:
monthly_sales = merged_df.groupby('close_month')['close_value'].sum().reset_index().sort_values(by='close_month',ascending = True)
monthly_sales = monthly_sales.reindex(range(1,13), fill_value=0)
monthly_sales

    close_month  close_value
1           4.0     721932.0
2           5.0    1025713.0
3           6.0    1338466.0
4           7.0     696932.0
5           8.0    1050059.0
6           9.0    1235264.0
7          10.0     731980.0
8          11.0     938943.0
9          12.0    1131573.0
10          0.0          0.0
11          0.0          0.0
12          0.0          0.0

#### average close days

In [85]:
a = merged_df['closing_days'].mean()
print(a)

47.98539710922366

## PHASE 5 - KPI Engineering

#### Total Revenue KPI

In [45]:
total_revenue = merged_df.loc[merged_df['deal_stage'] == 'Won', 'close_value'].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 6723

#### sales cycle length
Measures how long deals take to close

*first creating the time cycle

In [46]:
merged_df['sales_cycle_days'] = (merged_df['close_date'] - merged_df['engage_date']).dt.days

In [47]:
avg_sales_cycle = merged_df.loc[merged_df['deal_stage'] == 'Won', 'sales_cycle_days'].mean()
print("Average Sales Cycle (Days):", round(avg_sales_cycle,2))

Average Sales Cycle (Days): 133.0

#### revenue by sales agent

In [48]:
revenue_by_agent = merged_df.loc[merged_df['deal_stage'] == 'Won'] \
                    .groupby('sales_agent')['close_value'].sum() \
                    .sort_values(ascending=False)

revenue_by_agent

sales_agent
Darcel Schlecht    4564
Moses Frase        1642
Zane Levy           517
Name: close_value, dtype: object

#### which product earns most mone

In [49]:
merged_df[merged_df['deal_stage'] == 'Won'] \
    .groupby('product')['close_value'] \
    .sum() \
    .sort_values(ascending=False)

product
GTXPro            4514
GTX Basic         1105
GTX Plus Basic    1054
MG Special          50
Name: close_value, dtype: object

## Final Business Recommendations
### 1.Focus on High-Revenue Products
Increase marketing budget for top-performing products

Bundle low-performing products with high-performing ones
### Improve Low Win-Rate Areas
Analyze lost deals stage-wise

Identify common rejection reason

### Reduce Sales Cycle Length
Prioritize high-intent customers

Identify delay stages (Negotiation / Proposal)

### Reward & Replicate Top Agent Strategy
Use them for training junior agents

Introduce performance-based incentives.

#### Summary
Based on the KPI analysis and exploratory data findings, the company should focus on improving win rate, optimizing sales cycle efficiency, strengthening high-performing products, and leveraging top sales agent strategies. Implementing a data-driven performance monitoring system will significantly enhance revenue growth and operational efficiency.